### ISSUE TITLE
Possible to implement ->store method on field 

### ISSUE THREAD

**Issue by roarkmccolgan** [scbing/nova-images#3]
Hi There,

I was wondering if you thought about implementing the store method on the images field?
This would allow someone to modify images during upload, so they can crop, resize etc? 

As the normal image field [does](https://nova.laravel.com/docs/3.0/resources/file-fields.html#customizing-the-entire-storage-process)

Thanks!

**Comment by scbing** [comment]
You can use the event monitoring model to update the event, judge whether the images have changed, and compare the difference between the original value and the new value for image processing.

**Comment by roarkmccolgan** [comment]
Thank you! Thats a good solution
