### ISSUE TITLE
Javascript Error "e.toUpperCase is not a function"

### ISSUE THREAD

**Issue by roarkmccolgan** [scbing/nova-images#4]
Nova v3.8.2
Laravel 7.25
sbing/images ^3.0

Upon selecting an image I'm getting a javascript error "e.toUpperCase is not a function"

![image](https://user-images.githubusercontent.com/1567162/90342738-cbb2aa00-e00a-11ea-9cb4-877790e19ba5.png)

It looks like it might be coming from the currentLabel computed property in FormField.Vue but I'm not sure.

My production server is running Nova 3.6.0 and it works as expected.

![image](https://user-images.githubusercontent.com/1567162/90342831-7cb94480-e00b-11ea-8530-05a23c34faec.png)

Thank you.

**Comment by scbing** [comment]
> Nova v3.8.2
> Laravel 7.25
> sbing / images ^ 3.0
> 
> 选择图片后，我收到了JavaScript错误“ e.toUpperCase不是函数”
> 
> ![图片](https://user-images.githubusercontent.com/1567162/90342738-cbb2aa00-e00a-11ea-9cb4-877790e19ba5.png)
> 
> 看起来它可能来自FormField.Vue中的currentLabel计算属性，但我不确定。
> 
> 我的生产服务器正在运行Nova 3.6.0，并且可以按预期工作。
> 
> ![图片](https://user-images.githubusercontent.com/1567162/90342831-7cb94480-e00b-11ea-8530-05a23c34faec.png)
> 
> 谢谢。


I'll fix it when I come home from work today.

Thank you very much for pointing out the mistake.

**Comment by scbing** [comment]
> Nova v3.8.2
> Laravel 7.25
> sbing/images ^3.0
> 
> Upon selecting an image I'm getting a javascript error "e.toUpperCase is not a function"
> 
> ![image](https://user-images.githubusercontent.com/1567162/90342738-cbb2aa00-e00a-11ea-9cb4-877790e19ba5.png)
> 
> It looks like it might be coming from the currentLabel computed property in FormField.Vue but I'm not sure.
> 
> My production server is running Nova 3.6.0 and it works as expected.
> 
> ![image](https://user-images.githubusercontent.com/1567162/90342831-7cb94480-e00b-11ea-8530-05a23c34faec.png)
> 
> Thank you.

Thanks for feedback, I have fixed it. Please run the update command to make the version of sbing/nova-images reach 3.0.6
